/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: GSMRF (https://sketchfab.com/gsmrf)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/zombie-scream-4-f27f2d27abf647b9ac9122a930891841
Title: Zombie Scream (4)
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_90: THREE.SkinnedMesh
    Object_92: THREE.SkinnedMesh
    Object_93: THREE.SkinnedMesh
    Object_95: THREE.SkinnedMesh
    Object_96: THREE.SkinnedMesh
    Object_97: THREE.SkinnedMesh
    Object_99: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    ['Material.003']: THREE.MeshBasicMaterial
    ['Material.000']: THREE.MeshBasicMaterial
    ['Material.001']: THREE.MeshBasicMaterial
  }
}

type ActionName = 'mixamo.com'
type GLTFActions = Record<ActionName, THREE.AnimationAction>
type ScreamProps={
  animated:boolean;
  setAnimated:React.Dispatch<React.SetStateAction<boolean>>
}

const ZombieScream=(
  {animated,setAnimated,...props}:ScreamProps & JSX.IntrinsicElements['group']
) =>{
  const group = useRef<THREE.Group>()
  const screamRef=useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/assets/3d/zombie_scream_4.glb') as GLTFResult
  const { actions } = useAnimations(animations, screamRef)
  useEffect(()=>{
    const animation=actions['mixamo.com']
    if(animation){
      animation.play()
    }
  },[])
  return (
    <group ref={screamRef} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.189}>
          <group
            name="7bfe13faf3fc40f399ad272eb51b39cafbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature">
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_90"
                      geometry={nodes.Object_90.geometry}
                      material={materials['Material.003']}
                      skeleton={nodes.Object_90.skeleton}
                    />
                    <skinnedMesh
                      name="Object_92"
                      geometry={nodes.Object_92.geometry}
                      material={materials['Material.000']}
                      skeleton={nodes.Object_92.skeleton}
                    />
                    <skinnedMesh
                      name="Object_93"
                      geometry={nodes.Object_93.geometry}
                      material={materials['Material.003']}
                      skeleton={nodes.Object_93.skeleton}
                    />
                    <skinnedMesh
                      name="Object_95"
                      geometry={nodes.Object_95.geometry}
                      material={materials['Material.003']}
                      skeleton={nodes.Object_95.skeleton}
                    />
                    <skinnedMesh
                      name="Object_96"
                      geometry={nodes.Object_96.geometry}
                      material={materials['Material.001']}
                      skeleton={nodes.Object_96.skeleton}
                    />
                    <skinnedMesh
                      name="Object_97"
                      geometry={nodes.Object_97.geometry}
                      material={materials['Material.000']}
                      skeleton={nodes.Object_97.skeleton}
                    />
                    <skinnedMesh
                      name="Object_99"
                      geometry={nodes.Object_99.geometry}
                      material={materials['Material.003']}
                      skeleton={nodes.Object_99.skeleton}
                    />
                    <group
                      name="Object_89"
                      position={[-0.563, 751.153, -0.423]}
                      rotation={[-1.544, 0, 0]}
                      scale={100.557}
                    />
                    <group
                      name="Object_91"
                      position={[-0.563, 751.153, -0.423]}
                      rotation={[-1.544, 0, 0]}
                      scale={100.557}
                    />
                    <group
                      name="Object_94"
                      position={[13.998, 1246.001, 14.45]}
                      rotation={[-1.944, -0.223, 0.012]}
                      scale={102.11}
                    />
                    <group
                      name="Object_98"
                      position={[-0.563, 751.153, -0.423]}
                      rotation={[-1.544, 0, 0]}
                      scale={100.557}
                    />
                  </group>
                </group>
                <group
                  name="body002"
                  position={[-0.563, 751.153, -0.423]}
                  rotation={[-1.544, 0, 0]}
                  scale={100.557}
                />
                <group
                  name="body001"
                  position={[-0.563, 751.153, -0.423]}
                  rotation={[-1.544, 0, 0]}
                  scale={100.557}
                />
                <group
                  name="head007"
                  position={[13.998, 1246.001, 14.45]}
                  rotation={[-1.944, -0.223, 0.012]}
                  scale={102.11}
                />
                <group
                  name="body"
                  position={[-0.563, 751.153, -0.423]}
                  rotation={[-1.544, 0, 0]}
                  scale={100.557}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/3d/zombie_scream_4.glb')
export default ZombieScream